# Generated by Django 4.2.7 on 2023-12-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='customer',
        ),
    ]
