# Generated by Django 4.2.7 on 2023-12-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='acceleration',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='car',
            name='top_speed',
            field=models.CharField(default='', max_length=255),
        ),
    ]
